### ISSUE TITLE
handling empty cells with prepare_data

### ISSUE THREAD

**Issue by tahaceritli** [OxWearables/capture24#2]
Hi @chanshing ,

Thanks for maintaining this repo!

I had a minor issue when I ran prepare_data.py and fixed it. See https://github.com/activityMonitoring/capture24/pull/1. Not sure if others will have the same problem too though. I think it has something to do with pd.read_csv reading extra empty lines.

Best,
Taha

**Comment by chanshing** [comment]
Closed by https://github.com/OxWearables/capture24/pull/1
