### ISSUE TITLE
New Version of the CAPTURE-24 Dataset Seems to be Incomplete

### ISSUE THREAD

**Issue by bjm-123** [OxWearables/capture24#4]
Hi @chanshing 

First of all, thank you for sharing your valuable work and dataset! I am currently downloading the dataset from [here](https://ora.ox.ac.uk/objects/uuid:99d7c092-d865-4a19-b096-cc16440cd001) and I have encountered a small issue that I hope you could help me with.

According to the documentation, each data instance in the dataset should contain ~24 hours of data. However, after downloading and examining the dataset, I noticed that each instance seems to include only about ~3 hours of data (.csv file contains 1, 048, 576 rows of data record). 

Could you kindly verify if the dataset provided is complete? If there has been a mistake, would it be possible to provide the full 24-hour data for each instance? Any guidance on how to obtain the complete dataset would be greatly appreciated.

Thank you very much for your time and assistance! 

Best regards,
Jiameng

**Comment by chanshing** [comment]
Hi @bjm-123 can you share the participant number you looked at? Not all participants will have exactly 24h of data as some participants have worn it for more, others less

**Comment by bjm-123** [comment]
Dear @chanshing ,

Thank you for your reply! I discovered that there is no problem with the dataset. I used Microsoft Excel to open the .csv file and it supports displaying up to 1, 048, 576 rows of data, and I assumed the data was incomplete.

I apologize for my stupid question, and thank you again for your time and help!

Best regards,
Jiameng

**Comment by chanshing** [comment]
No problem! Glad it got fixed
